---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30100
    port: 5000
    protocol: TCP
    name: api
    targetPort: 5000
  selector:
    app: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: demo-app/backend
        imagePullPolicy: Never
        env:
        - name: DB_URL
          value: "postgresql://postgres:password@postgresql:5432/postgres"
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: FLASK_ENVIRONMENT
          value: "production"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
            httpHeaders:
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3