apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  labels:
    name: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      name: backend
  endpoints:
  - port: api